title: DigiMed Wiki
description: DigiMed encyclopedia

theme: jekyll-theme-slate

collections:
  elasticsearch:
    output: true
    defaults:
      -
        tags: [elasticsearch]

  git:
    output: true
    defaults:
      -
        tags: [git]
